name: Sync Upstream and Update Submodules

on:
  workflow_dispatch:
  schedule:
    # Runs at minute 0 past every 2nd hour
    - cron: '0 */2 * * *'

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: beta
        submodules: 'true'

    - name: Sync Official Modules Upstream
      env:
        GH_TOKEN: ${{ secrets.MODULE_SYNC_PAT }}
      run: |
        echo "Syncing modules in the Official directory..."
        find Official/ -name "jasp[A-Z]*" -type d | sed "s/.*\///" | xargs -I {} gh repo sync jasp-stats-modules/{} --source jasp-stats/{} --branch master --force

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "github-actions@github.com"

    - name: Update submodules
      run: |
        # Updates submodules based on the branch specified in your .gitmodules file
        git submodule update --remote

    - name: Commit and Push Directly to Beta
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "Changes detected in submodules. Committing..."
          
          git add .
          git commit -m "chore: automated upstream sync and submodule update"
          
          git push origin HEAD:beta
          
          echo "Successfully pushed updates to beta."
        else
          echo "No changes to submodules detected. Skipping push."
        fi
